pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - "status-success=ci/circleci: validate"
    actions:
      merge:
        method: merge
      comment:
        message: "Thank you Scala Steward! :heart:"
